import Head from 'next/head'
import Img from 'next/image'
import Link from 'next/link'
//import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div >
      <Head>
        <title>BID Impact Program</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >




        {/* Hero section */}
        <div > 
          <div className="relative z-20 flex items-center overflow-hidden bg-gray-800 dark:bg-gray-800 background h-screen  w-full ">
              <div className="container relative flex justify-between px-6 py-16 mx-auto">
                  <div className="px-5 md:px-20 relative z-20 flex flex-col sm:w-2/3 lg:w-2/5">
                      <span className="w-40 h-4  md:pl-1.5 text-white"> BID Presents
                      </span>
                      <h1 className="flex justify-centre flex-wrap text-6xl lg:text-8xl font-black leading-none text-white uppercase font-bebas-neue  dark:text-white">
                          <span className='text-amber-500'>IMPACT</span>
                          <span>PROGRAM</span>
                          
                      </h1>
                      <p className="text-lg text-white  md:text-base dark:text-white">
                          A 3-month program to give boost to the growth of impact creating bussinesses and communities by adopting the core of blockchain technology. 
                      </p>
                      <div className="flex mt-8">
                          <Link href="/projects" className="flex items-center px-4 py-2 mr-4 text-white uppercase bg-amber-500 border-2 border-transparent rounded-lg text-md hover:bg-amber-400">
                              Contribute
                          </Link>
                          <Link href="/about" className="px-4 py-2 text-amber-600 uppercase bg-transparent border-2 border-amber-500 rounded-lg dark:text-white hover:bg-amber-400 hover:text-white text-md">
                              Learn more
                          </Link>
                      </div>
                  </div>
                  <div className=" relative hidden sm:block md:w-1/3 lg:w-3/5">
                      <Img
                        src="/bid.png" className=" max-w-xs m-auto md:max-w-sm"
                        width={500}
                        height={500}
                        alt="Impact Program"
                      />
                  </div>
              </div>
          </div>
        </div>





        {/* About section */}

        <div id="about"  className="relative z-50 flex items-center overflow-hidden bg-white dark:bg-white background h-screen  w-full ">
          <div className="container relative  flex px-4 py-4   mx-8">
            <div className=" md:flex justify-between w-full px-4 mx-auto lg:w-4/5">
              <div className='text'>
                <h1 className='text-2xl font-bold md:text-4xl text-black '>
                  About Impact Program
                </h1>
                <p className='text-sm md:text-xl text-black pt-5'>
                  We are going to build and grow communites and bussiness which create an positive impact on the way of learning and developing the world into a better place. We are building these communites publicly and everyone can contribute in them an and become the part of next future.All the communities and Dao are value based and transparent and we are going to use the power of blockchain technology to make them more secure and trustable.
                </p>
              </div>
              <div className='md:width-3000 flex items-center'>
                <Img src = '/1.png' width={3000} height={3000} alt='About' />
              </div>
            </div>
          </div>
        </div>




        {/* three card section */}
        <div id="cards"  className="relative z-50 flex items-center overflow-hidden bg-black dark:bg-black background h-screen md:h-[32rem]  w-full ">
          <div className='container relative flex px-4 py-4   mx-8'>  
            <div className='mt-6 md:gap-x-10 md:flex justify-center'>
              <div className='my-6 w-full md:w-2/5 lg:w-1/5 lg:h-60 block p-6 rounded-lg shadow-3xl  bg-white hover:bg-bb3 max-w-sm-wrap items-center'>
                <div className='flex justify-center mb-3'>
                  <Img src = '/apply.svg' width={40} height={40} alt='apply'  />
                </div>
                <h1 className='text-gray-900 text-xl leading-tight font-semibold mb-2 flex justify-center'>Apply</h1>
                <p className='text-gray-700 text-base mb-4 text-center  '>Interested contributors propose a project to work on.</p>
              </div>
              <div className='my-6 w-full md:w-2/5 lg:w-1/5 block p-6 rounded-lg shadow-3xl bg-white  hover:bg-bb3 max-w-sm-wrap items-center'>
                <div className='flex justify-center mb-3'>
                  <Img src = '/contribute.svg' width={40} height={40} alt='contribute'  />
                </div>
                <h1 className='text-gray-900 text-xl leading-tight font-semibold mb-2 flex justify-center'>Contribute</h1>
                <p className='text-gray-700 text-base mb-4 text-center'>Accepted contributors spend the 3-month with guidance from a mentor to create impact</p>
              </div>
              <div className='my-6 w-full md:w-2/5 lg:w-1/5 block p-6 rounded-lg shadow-3xl bg-white  hover:bg-bb3 max-w-sm-wrap items-center'>
                <div className='flex justify-center mb-3'>
                  <Img src = '/share.svg' width={40} height={40} alt='share'  />
                </div>
                <h1 className='text-gray-900 text-xl leading-tight font-semibold mb-2 flex justify-center'>Share</h1>
                <p className='text-gray-700 text-base mb-4 text-center'>Submit your contribution for the next world to use!</p>
              </div>
            </div>
          </div>  
        </div>
        

      </main>

      
    </div>
  )
}
